baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Andrew Garrison"

[params]
  description = "Andrew Garrison is a UX Developer and Designer from Omaha, NE"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Projects"
    url  = "/projects"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/blog"
    weight = 3
[[menu.main]]
    name = "Now"
    url  = "/now"
    weight = 4