backend:
  name: git-gateway
  repo: andrewgarrison/atgarrison.com
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img"

collections:
  name: "posts"
  label: "Blog Post"
  folder: "site/content/blog/posts"
  create: true
  fields:
    - {label: "Name of Post", name: "title", widget: "string"}
    - {label: "Category", name: "Categories", widget: "string"}
    - {label: "Type", name: "type", widget: "select", options: ["posts", "project"]}
    - {label: "Description", name: "Description", widget: "string"}
    - {label: "Feature Image", name: "feature_image", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}